apiVersion: v1
kind: Secret
metadata:
    name: gitops-smoke
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:kjCYw+wctP3zvVqCfpsy6oM9O6YPYVViRZO6AVPRAOb9GMluXdoRmjUfM3f9sovE,iv:WLzYQXTVZ5V0hjCrDaWdITKAyl3wk0H6CpAszVvFfmE=,tag:Dw9QdW7R+UdyJrXvPiyQQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d3FPd3c5SmFBdkFpZ1Ni
            cVRUWEp5MjJPYyt2YVowZUJTNVlCNk9aazJFCi9ISzZaeEFJK0hhT2lZR0NmMnRS
            Ync4ZDlGOGtpeEc1bjFRWktjWHZHQ0EKLS0tIHo4ZG4vbk5RWkkrVFRVUzBBU21x
            cUMvdmVPSnU2Yld4ME9BeEpjTXJSUTQKRAn3cEu5lBbN0GWW4uNXBZMn4dImO9Yv
            e98pwrEVJfopUWvpcRYvReIa8JsBTsnYEihHcU+o3faGrkUn0ZVLxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vqhscpppn2trashhqzg2c5jp0zrhmj6e26pum9rk8s4mf07eqchqacgyyq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T17:03:31Z"
    mac: ENC[AES256_GCM,data:L/IXEq2+pFwp4+xZCuehEblAbtPZAe7L5ZhY0nIqXU3yq4fhGL/8h0En7KKQoEvAChqE+llFWP28l+qojnCyX27ES5CyW5KOBcd3BAMBKKr0nel2kiBkTD2MGawNCVaX+/dFCTwYc415qQHOGSCSyJwHwd+jzpa4xQN3dpDkp34=,iv:sJxsIgw0Ok9Nhsq2oR+vAN7G0qoBexi3HpKB9+X0Cog=,tag:FNCnGTzUre3Wh71j2m1QeA==,type:str]
    version: 3.13.2
