FROM quay.io/argoproj/argocd:v3.4.2
USER 0
COPY sops /usr/local/bin/sops
RUN echo "154dfe4cd70554bdd82b98e4cd4acf191d43d01ead6f00a73477aa44c4ac42ef  /usr/local/bin/sops" | sha256sum -c - \
    && chmod 0755 /usr/local/bin/sops
USER 999
