spec:
  template:
    spec:
      volumes:
        - name: cmp-sops-tools
          $patch: delete
        - name: cmp-sops-config
          configMap:
            name: argocd-cmp-sops
        - name: cmp-sops-age
          secret:
            secretName: sops-age
        - name: cmp-tmp
          emptyDir: {}
      initContainers:
        - name: install-sops
          $patch: delete
      containers:
        - name: sops-kustomize
          image: homelab/argocd-sops:v3.4.2-sops3.13.2
          imagePullPolicy: Never
          command: [/var/run/argocd/argocd-cmp-server]
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /usr/local/bin/sops
              $patch: delete
            - name: var-files
              mountPath: /var/run/argocd
            - name: plugins
              mountPath: /home/argocd/cmp-server/plugins
            - name: cmp-sops-config
              mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
            - name: cmp-sops-age
              mountPath: /home/argocd/.config/sops/age
              readOnly: true
            - name: cmp-tmp
              mountPath: /tmp
