apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge-smoke
spec:
  ingressClassName: traefik
  rules:
    - host: edge-smoke.app.kayage.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edge-smoke
                port:
                  name: http
